[[redirects]]
  from = "/https://riszartdaryl.netlify.app/*"
  to = "/https://riszartdaryl.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/https://www.riszartdaryl.netlify.app/*"
  to = "/https://www.riszartdaryl.site/:splat"
  status = 301
  force = true