[[redirects]]
  from = "/riszartdaryl.netlify.app/*"
  to = "/https://riszartdaryl.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/www.riszartdaryl.netlify.app/:splat"
  to = "https://www.riszartdaryl.site/:splat"
  status = 301
  force = true