[[redirects]]
  from = "https://riszartdaryl.netlify.app/*"
  to = "https://riszartdaryl.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://riszartdaryl.netlify.app"
  to = "https://riszartdaryl.site"
  status = 301
  force = true

[[redirects]]
from = "/.netlify.app"
to = "/.site"
status = 301
force = true
